export {default as Home } from "./Home"
export {default as Navbar } from "./Navbar"
export {default as Activities} from "./Activities"
export {default as Routines } from "./Routines"
export {default as SingleRoutine } from "./SingleRoutine"
export {default as MyRoutines } from "./MyRoutines"
export {default as Login } from "./Login"
export {default as Register } from "./Register"
