export {default as Home } from "./Home"
export {default as Navbar } from "./Navbar"
export {default as Footer } from "./Footer"
export {default as Activities} from "./Activities"
export {default as CreateActivity } from "./CreateActivity"
export {default as AddActivity} from "./AddActivity"
export {default as EditActivity} from "./EditActivity"
export {default as Routines } from "./Routines"
export {default as CreateRoutine } from "./CreateRoutine"
export {default as SingleRoutine } from "./SingleRoutine"
export {default as MyRoutines } from "./MyRoutines"
export {default as Login } from "./Login"
export {default as Register } from "./Register"
export {default as Profile } from "./Profile"

